### ISSUE TITLE
Bug: Using `DRY_RUN: false` still triggers a dry run

### ISSUE THREAD

**Issue by efirestone** [van-geaux/plex_nfo_exporter#25]
If, in your Docker Compose, you set the `DRY_RUN` variable to `false`, you still end up getting dry run mode. I suspect because the code simply evaluates the presence of this variable and not its "truthiness".

FWIW, I'm using the YAML mapping syntax for the environment, and not the array syntax, although I suspect it doesn't matter:

```
    environment:
      CRON_SCHEDULE: 0 4 1 * * # First day of each month, at 4AM
      RUN_IMMEDIATELY: true
      DRY_RUN: false
      TZ: ${timezone}
```

Thanks for the great tool!
